import Head from 'next/head'
import Image from 'next/image'
import CreateGlobalStyle from '../../styles/global-style'
import * as S from "./style"

export default function Home() {
  return (
    <>
      <CreateGlobalStyle />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          
          <S.Title>ola</S.Title>
    </>
  )
}
